### ISSUE TITLE
Past history on new wiped install is retained

### ISSUE THREAD

**Issue by 7h3v01c3** [DiviProject/Divi-Desktop-Public#126]
On a wiped new install it should also no longer display our data store of previously used addresses or meta data. PLUS test-net data shouldn't show on main-net history
uninstalled app, new datadir
This what a normal user may do to totally reset or move data from one machine to another ... they may not want history of old transactions or addresses

1.5.8 +

![image](https://user-images.githubusercontent.com/16604693/70145916-c7a25000-1666-11ea-95ef-ddc495b240aa.png)

┆Attachments: <a href="https://storage.www.wrike.com/attachments/144195683?accountId=2811331">Image-2020-05-06 16-16-52.png</a>

**Comment by 7h3v01c3** [comment]
This is a duplicate that will be fixed with https://github.com/DiviProject/Divi-Desktop-Public/issues/142

**Comment by Divicoin** [comment]
➤ The Voice commented:

This can be fixed by also deleted the data with uninstall removing everything from the following locations. 

I would call remove all Divi Desktop Information and Wallet data from this computer

It should have a **pop up warning** and maybe an offer before hand that suggests an export. With a button to our export wallet option.

After approving

Remove

C:\Program Files\Divi Desktop
but also 
C:\Users\Username\AppData\Roaming\DIVI"
C:\Users\Username\AppData\Roaming\Divi Desktop

**Comment by Divicoin** [comment]
➤ The Voice commented:

Elías Gómez can you give an idea on this option please
