### ISSUE TITLE
Pagination should start from top

### ISSUE THREAD

**Issue by Divicoin** [DiviProject/Divi-Desktop-Public#53]
When skipping pages in the transaction history, show the list from the top rather than the bottom as it is currently.

**Comment by oriz456** [comment]
Looks like any option to go to the next/last page from the bottom has been removed. Ideally I think the option should exist both from the top as well as the bottom in order to avoid unnecessary back and forth scrolling, but the next page should always start up top, even if you used the bottom "next" or arrow.
